name: .NET 9.0 Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        cache: true
        cache-dependency-path: '**/packages.lock.json'
      
    - name: Display .NET info
      run: dotnet --info
      
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quiz-app-${{ matrix.os }}
        path: ./bin/Release/
        if-no-files-found: warn